#copied from https://github.com/gentoo-haskell/gentoo-haskell/blob/fb0ac412f913333acce5136cc1b6b2f0ed1e5c29/.github/workflows/repoman.yml
name: repoman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All "stable" profiles are listed here, but only amd64 and x86 profiles
        # are actually used, since these are the only two architectures
        # currently supported by ghc.
        #
        # Some of the profiles are "doubled up" - in other words, we run two
        # profiles for some of the "jobs". The reason for this is to keep the
        # total number of jobs for the `repoman` "github action" at 19.
        #
        # Since github allows us 20 concurrent "actions" at once, this maximizes
        # the number of parallel jobs while still allowing one job for the
        # `pkgcheck` action.
        #
        # Feel free to double up more of these if needed, or uncomment
        # architectures.
        profile:
          # - default/linux/amd64/17.1 default/linux/amd64/17.1/selinux
          # - default/linux/amd64/17.1/hardened default/linux/amd64/17.1/hardened/selinux
          # - default/linux/amd64/17.1/desktop
          - default/linux/amd64/23.0/split-usr
          - default/linux/amd64/23.0/split-usr/desktop
          - default/linux/amd64/23.0/split-usr/hardened default/linux/amd64/23.0/split-usr/hardened/selinux
    env:
      PROFILE: ${{ matrix.profile }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Setup repoman
      run: |
        python -m pip install --upgrade pip
        pip install lxml pyyaml
        wget -qO - "https://github.com/gentoo/portage/archive/portage-3.0.30.tar.gz" | tar xz
        sudo groupadd -g 250 portage
        sudo useradd -g portage -d /var/tmp/portage -s /bin/false -u 250 portage
    - name: Setup master gentoo repository
      run: |
        sudo mkdir -p /var/db/repos/gentoo /etc/portage /var/cache/distfiles
        wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | sudo tar xz -C /var/db/repos/gentoo --strip-components=1
        sudo wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
        sudo wget "https://gitweb.gentoo.org/proj/portage.git/plain/cnf/repos.conf" -O /etc/portage/repos.conf
        sudo ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/23.0 /etc/portage/make.profile
    - name: Test with repoman
      run: |
        python3 portage-portage-3.0.30/repoman/bin/repoman full -dx --jobs=$(nproc) --include-profiles="${PROFILE}"
